//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int ContactoId { get; set; }
        public Nullable<int> userID { get; set; }
        public string Nombre_Contacto { get; set; }
        public string Apellido_Contacto { get; set; }
        public string Numero_Contacto { get; set; }
        public string Correo_Contacto { get; set; }
    
        public virtual UserAgenda UserAgenda { get; set; }
    }
}
